### ISSUE TITLE
demo doesn't work

### ISSUE THREAD

**Issue by diomed** [douglasgough/foundational#1]

**Comment by douglasgough** [comment]
I'll need more information. The theme doesn't include any demo content.

**Comment by diomed** [comment]
https://foundational.douggough.com

doesn't work

**Comment by douglasgough** [comment]
Ok. The url is wrong. I'll update it. Thanks

**Comment by douglasgough** [comment]
I've fixed in in the repository. The fix should be pulled to the Grav site soon.
